### ISSUE TITLE
Device status inverted in zone device card

### ISSUE THREAD

**Issue by hrc007** [jreenen/com.jreenen.homeyharmonyhub#14]
Homey Firmware Versie: 1.5.3
Homey Harmony Hub Beta : v1.2.0

Device state in zone devicecard is inverted. Example tv device has device card status on, but in fact the tv is off. When i change the device card state to off my tv goes on.

**Comment by jreenen** [comment]
@hrc007 
Thanks for your report! Think the problem is that at the moment the apps use kind of a poor man's solution for the on/off control. It's triggering the power toggle command on the hub even if the device supports separate on and off commands. Can you confirm that the initial on/off state is correctly synced with the current activity?

**Comment by hrc007** [comment]
Hi I am not completly sure what you mean, but when is send a power on command via the flow manager device card, the tv goes on, but the device state in zone/ device card is not synced.

**Comment by hrc007** [comment]
Hi this one is working aswell Thanks
