### ISSUE TITLE
Can not find TV, receiver

### ISSUE THREAD

**Issue by stanman23** [jreenen/com.jreenen.homeyharmonyhub#24]
First of all i love the app. Most of the time it works perfect. I have a couple of things to report. 

- When i update/sync my hub Homey wont control them any more. Last time i updated the hub, my 10 flows where still there, no broken links but also (on test) no connection whit the receiver. It keeps trying. When i uninstall the hub and install it again every thing works fine....

- On the hub are my TV (samsung), receiver (Denon), Ziggo box (samsung). When i tell homey to turn off the TV it says that it can not find a tv. (i did select the tv, it says its a tv and it has an tv icon). But it wont work. Now i wrote some flows (when I say "TV" or "Television" off) It has a conflict (homey has tv as standaard). But now it works almost fine. Somtimes it still says that it has no tv, after a 2nd time it has. 

- The same whit the receiver. When i Say put the volume on 20 it says that is has no receiver. So i had to write every line of volume... (and it says that is has conflicts on all) But is does work. But if there is an error i have to rewrite them all...:(. 

- Also on the receiver, i can not say put chanel 4 on becouse it can not see it. 

I looked for the node information off them all but there is no configuration on them. Only the on off switch.

**Comment by jreenen** [comment]
@stanman23 sorry for my extremely late response. 

- The behavior you describe is caused by some caching mechanism that was implemented on this app. At the moment it isn't that smart that it is detecting when changes happen on the hub. You don't have to reinstall the hub, restarting the application does the trick also.
- TV and televison are reserved words on the homey at this moment a TV on the harmony hub is not matched as a TV on homey please keep an eye on this [issue](https://github.com/jreenen/com.jreenen.homeyharmonyhub/issues/8) because this should solve it.
- For the receiver same story as TV

I hope this answers you questions? If not feel free to re-open this issue
